DeveloperAcademy-POSTECH/MC2-morning-Team12-DreamLog

- .gitignore
> Setting - gitignore 추가

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/Global/Extension/ColorExtension.swift
Global/Extension/ColorExtension.swift
작업한 브랜치
- setting/ColorExtension - 커스텀 색상 추가 #9
- 색상 관련 설명 주석에 적어놓았습니다.
- resolved : #9
> [Setting] #9 - 커스텀 색상 추가

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/Global/Extension/ViewExtension.swift
- mc2-DreamLog/mc2-DreamLog/Global/Modifier/ButtonBrownModifier.swift
- mc2-DreamLog/mc2-DreamLog/Global/Modifier/ButtonWhiteBoldModifier.swift
- mc2-DreamLog/mc2-DreamLog/Global/Modifier/TextBrownModifier.swift
- mc2-DreamLog/mc2-DreamLog/Global/Modifier/TextGrayModifier.swift
작업한 브랜치
- Setting/#15
- x
- resolved : #15
> [Setting] DreamLog #15 - Modifier추가

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/View/CheerLogView.swift
- mc2-DreamLog/mc2-DreamLog/View/MainView.swift
작업한 브랜치
- feature/#23 
- 응원로그 상단에 타이틀을 추가했습니다
- 한 번에 할랬는데, 내일 CRUD를 해볼 예정이라 그냥 디자인은 따로 빼서 Issue를 만드는 것이 나을 것 같아서 따로 하겠습니다
- resolved : #23
> [Design]#23 CheerLog - 타이틀 추가

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
작업한 브랜치
- feature/ #33 
- [TutorialTextEditView] 폰트 사이즈 조절
- [TutorialTextEditView] 폰트 컬러 조절
- [TutorialTextEditView] 폰트 선택
- [TutorialTextEditView] 텍스트 이미지로 변경
- 제작한 Image를 받을 list를 바인딩해주는 기능은 구현하지 않음
- 이후 TutorialBoardView 구조 확정 후 바인딩 기능 추가 구현 필요
- resolved : #33
> [Feat]#33 DreamLog - TutorialTextEditView 텍스트 추가 기능 구현

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/Model/BoardElement.swift
- mc2-DreamLog/mc2-DreamLog/Model/FocusUUID.swift
- mc2-DreamLog/mc2-DreamLog/Model/TutorialBoardElement.swift
- mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
- mc2-DreamLog/mc2-DreamLog/View/Componets/FixableImageView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
- mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
작업한 브랜치
- feature/ #36
-
- resolved : #36
> [Feat]DreamLog #36 - 튜토리얼 보드뷰 드래그 삭제 기능 추가

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
- mc2-DreamLog/mc2-DreamLog/View/CheerLogView.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
- mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
작업한 브랜치
- feature/#31
- Core Data를 이용한 응원 로그 CRD 생성
- 리스트 디자인
- 없습니다 ㅋㅋ
- resolved : #31
> Feature/#31 CheerLog - CRUD 리스트 만들기

- mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
작업한 브랜치
- feature/ #46
- x
- resolved : #46
> [Chore] DreamLog #46 EditMenuView 버튼 선택 화면이동 추가

- mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
작업한 브랜치
- feature / #47 
Canvas에서 UIImage로 변환 기능 추가, 변환된 이미지 사이즈를 그림사이즈에 맞게 조절하는 기능 추가
- x
- resolved : #47
> [Feat] #47  DreamLog - 그린 그림을 이미지로 변환 

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/Global/Extension/ColorExtension.swift
- mc2-DreamLog/mc2-DreamLog/Model/ColorPreset.swift
- mc2-DreamLog/mc2-DreamLog/View/Componets/EditColorView.swift
- mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
작업한 브랜치
- feature/ #53 
- Color Preset 만들기
- Color extension 변경
- 
- resolved : #53
> Feature/#53 Color Preset 만들기

- mc2-DreamLog/mc2-DreamLog/Model/TutorialBoardElement.swift
- mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
- mc2-DreamLog/mc2-DreamLog/View/Componets/FixableImageView.swift
- mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
작업한 브랜치
- feature/#52
- BoardElement 위치 position에서 offset으로 변경
-
- resolved : #이슈번호
> [Refactor] DreamLog #52 - BoardElement 위치 position에서 offset으로 변경

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/View/Componets/ShareSheet.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
작업한 브랜치
- Feat/#57 
- 
- resolved : #57
> [Feat] DreamLog #57 - 공유버튼에 기능 할당

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
- mc2-DreamLog/mc2-DreamLog/View/Componets/WidgetAreaView.swift
- mc2-DreamLog/mc2-DreamLog/View/Componets/WidgetSizeButtonsView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
작업한 브랜치
- feature/ #69 
- 편집에서 위젯 영역을 표시해주는 기능 구현
- WidgetAreaView: 위젯에서 보여지는 부분만 보여주는 View
- WidgetSizeButtonsView: 위젯 사이즈를 보여주는 버튼 view
- resolved : #69
> [Feat] DreamLog#69 - TutorialBoardView - WidgetSize 보여주는 기능 구현

- mc2-DreamLog/mc2-DreamLog/Global/Extension/ColorExtension.swift
- mc2-DreamLog/mc2-DreamLog/Model/ColorPreset.swift
작업한 브랜치
- feature / #82 
- ColorExtension, ColorPreset에 색상 추가 (Black & White)
- x 
- resolved : #82
> [Feat] Color Preset #82 - ColorExtension, ColorPreset에 색상 추가 (Black & White)

- mc2-DreamLog/DreamBoardWidget/Assets.xcassets/AccentColor.colorset/Contents.json
- mc2-DreamLog/DreamBoardWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
- mc2-DreamLog/DreamBoardWidget/Assets.xcassets/Contents.json
- mc2-DreamLog/DreamBoardWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
- mc2-DreamLog/DreamBoardWidget/DreamBoardWidget.intentdefinition
- mc2-DreamLog/DreamBoardWidget/DreamBoardWidget.swift
- mc2-DreamLog/DreamBoardWidget/DreamBoardWidgetBundle.swift
- mc2-DreamLog/DreamBoardWidget/DreamBoardWidgetLiveActivity.swift
- mc2-DreamLog/DreamBoardWidget/Info.plist
- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
작업한 브랜치
- feature/#48
-  Widget 기본틀만 생성
-
- resolved : #48
> [Feat] DreamLog #48 - Widget 기본틀만 생성

- mc2-DreamLog/mc2-DreamLog/Global/Extension/ColorExtension.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
- mc2-DreamLog/mc2-DreamLog/View/MainView.swift
작업한 브랜치
- feature/ #77 
- Tab1 View 레이아웃 수정
- Tab1 응원문구 작성시 표시
- Tab Bar 아이콘 및 이름 수정
-
- resolved : #77
> [Feat] Tab1 View 레이아웃 수정 및 응원 문구 표시

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/Global/Extension/UIViewExtension.swift
- mc2-DreamLog/mc2-DreamLog/Global/Extension/ViewExtension.swift
- mc2-DreamLog/mc2-DreamLog/Model/BoardElement.swift
- mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
- mc2-DreamLog/mc2-DreamLog/Model/ImageFileManager.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
작업한 브랜치
- Feat/#32
- 보드 요소 저장 불러오기 함수 구현
-
- resolved : #32
> [Feat] DreamLog #32 - DBHelper 보드 요소 저장 불러오기 함수 구현

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
- mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
작업한 브랜치
- feature/#97
-  DreamBoardEditView 기능 구현
-
- resolved : #97
> [Feat] DreamLog#97 - DreamBoardEditView 기능 구현

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog.xcodeproj/xcshareddata/xcschemes/DreamBoardWidgetExtension.xcscheme
- mc2-DreamLog/mc2-DreamLog.xcodeproj/xcshareddata/xcschemes/mc2-DreamLog.xcscheme
- mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
- mc2-DreamLog/mc2-DreamLog/Model/DreamLogModel.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
- mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
작업한 브랜치
- feature/#99
- DreamBoardEditView 기능만 구현
- 이미지 해상도 줄이지 않아서 화면 넘어갈때 버벅거리는 상황
- 튜토리얼에서 드림보드 만들고 난 후에 앱 종료하고 다시 키면 수정이 불가했던 버그 해결
- resolved : #99
> [Feat] DreamLog/#99 - DreamBoardEditView 기능만 구현

- mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
작업한 브랜치
- Fix/#103
- 
- resolved : #103
> [Fix] DreamLog #103 DreamBoardEdit 화면 전환 방식 수정하기

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog.xcodeproj/xcuserdata/kimtaehyung.xcuserdatad/xcschemes/xcschememanagement.plist
- mc2-DreamLog/mc2-DreamLog/View/DDayCalendarView.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialCalendarView.swift
작업한 브랜치
- feature/디데이 계산 #94 
- 디데이 계산
- 디데이 계산
- resolved : #94
> Feature/#94 - 디데이 계산

- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
작업한 브랜치
- Fix/#107
- 레이아웃 긴급패치
- 레이아웃 긴급패치
- db관련 수정사항 없음
- resolved : #107
> [Fix] DreamLog #107 레이아웃 긴급패치

- mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
작업한 브랜치
- Fix/ #110
- 아직 완전히 렉이 사라지진 않았습니다.
- 일단 하나하나씩 줄여나가는 중입니다.
- resolved : #110
> [Fix] DreamLog #110 최적화 패치 -> 기존에 있던 이미지 삭제 후 새로운 이미지 추가

- mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
- mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
작업한 브랜치
- Fix/ #112
-
- resolved : #112
> [Fix] DreamLog #112 DBHelper 싱글톤 패턴 적용

- mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
- mc2-DreamLog/mc2-DreamLog/Model/DreamLogModel.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamLogView.swift
- mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
작업한 브랜치
- Feat/ #114
- 두번째 탭 데이터 관련 처리
-
- resolved : #114
> [Feat] DreamLog #114 - 두번째 탭 데이터 관련 처리

- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
작업한 브랜치
- feature/ #122 
- TutorialBoardView 진입 전 입력된 텍스트 폰트 적용
- 
- resolved : #122
> [Fix] DreamLog#122 - TutorialBoardView 진입 전 입력된 텍스트 폰트 적용

- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
작업한 브랜치
- Chore/ #133
- 
- resolved : #133
> [Chore] DreamLog #133 응원 확인 버튼시 알림창 텍스트 필드 초기화

- mc2-DreamLog/mc2-DreamLog/View/CheerLogView.swift
작업한 브랜치
- Design/ #135
- 
- resolved : #135
> [Design] DreamLog #135 - CheerLogView 탭 디자인 다른 뷰와 통일

- mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
작업한 브랜치
- feature/ #139 
- 보드 저장시 위젯 사이즈 캡쳐 오류 수정
-
- resolved : #139
> [Fix] DreamLog#139 - 보드 저장시 위젯 사이즈 캡쳐 오류 수정

- mc2-DreamLog/mc2-DreamLog/View/CheerLogView.swift
- mc2-DreamLog/mc2-DreamLog/View/DreamLogView.swift
작업한 브랜치
- feature/ #147
- Tab1, Tab2 상단 디자인 수정
- shadow 제거 및 divider 추가
-
- resolved : #147
> [Fix] DreamLog#147 - Tab1, Tab2 상단 디자인 수정

- mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
작업한 브랜치
- feature / #149 
- x
- resolved : #149
> [Fix] EditDrawingView - 붓 두께 기본값 조절, 버튼 하단 짤림 수정

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
작업한 브랜치
- feature/ #152 
- TutorialTextEditView 텍스트 이미지 해상도 default fontSize를 100으로 해서 높임
-
- resolved : #152
> [Fix] DreamLog#152 - TutorialTextEditView 텍스트 이미지 해상도 높이기

- mc2-DreamLog/mc2-DreamLog/View/LoadingView.swift
작업한 브랜치
- feature/ #151 
- LoadingView에서 보여주는 process indicator 디자인 수정
-
- resolved : #151
> [Fix] DreamLog#151 - Process indicator 디자인 수정(LoadingView)

- mc2-DreamLog/mc2-DreamLog/View/Componets/FixableImageView.swift
작업한 브랜치
- feature/#155 
- 제곧내
-
- resolved : #155
> [Add] DreamLog#155 - 회전 버튼 크기 및 색상 조정

- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
작업한 브랜치
- feature/#154 
- 이하동문
-
- resolved : #154
> [Fix]DreamLog#154 - 글자 클릭 시에도 alert창 뜨게하기

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/Global/Extension/UIApplication.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
작업한 브랜치
- feature/#156
- 이하동문
-
- resolved : #156
> [Add] DreamLog#156 - 키보드 올라온 뒤에 화면 터치 시 키보드 다시 내리기

- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialCalendarView.swift
작업한 브랜치
- feature/#161 
- 이하동문
-
- resolved : #161
> [Feat]DreamLog#161 - 튜토리얼 위젯뷰 추가

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
작업한 브랜치
- feature/#166
- EditMenuView - 드림보드 수정시 전체 삭제버튼 구현
-
- resolved : #166
> [Feat] DreamLog#166 - EditMenuView - 드림보드 수정시 전체 삭제버튼 구현

- mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
작업한 브랜치
- feature/ #171 
- 수정 아이콘 사이즈 조절
- 응원 문구 위치 변경
-
- resolved : #171
> [Fix] DreamLog#171 - Tab1 아이콘 수정 및 응원 문구 위치 수정

- mc2-DreamLog/DreamBoardWidget/DreamBoardWidget.swift
- mc2-DreamLog/mc2-DreamLog/Global/Extension/DBHelperExtension.swift
- mc2-DreamLog/mc2-DreamLog/Model/ImageFileManager.swift
- mc2-DreamLog/mc2-DreamLog/View/DDayCalendarView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
작업한 브랜치
- Chore/ #176
- 튜토리얼에서 데이터 안 넘어가는 것 개선??
-
- resolved : #176
> [Chore] DreamLog #176 튜토리얼에서 데이터 안 넘어가는 것 개선??

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/View/DreamLogView.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialCalendarView.swift
작업한 브랜치
- Fix/ #178 
- 캘린더 subtitle변경
- 디테일뷰 사진 리사이즈
- 앱 이름 표시 변경 -> DreamLog
-
- resolved : #178
> [Fix] DreamLog #178 캘린더 subtitle변경, 디테일뷰 사진 리사이즈, 앱 이름 표시 변경

- mc2-DreamLog/mc2-DreamLog/Global/Extension/DBHelperExtension.swift
- mc2-DreamLog/mc2-DreamLog/Global/Protocol/DreamLogTableProtocol.swift
- mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
작업한 브랜치
- Feat/ #180
- TutorialBoard에서 화면 넘어가기전에 alert 만드는 거 안해도 될듯 합니다.
- resolved : #180
> [Feat] DreamLog #180 TutorialBoard <-> Calendar 왔다갔다해도 로그 데이터는 하나만 저장

- mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
- mc2-DreamLog/mc2-DreamLog/Info.plist
- mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
작업한 브랜치
- Fix/ #188 
- 다크모드 미실행 설정
- 전체삭제버튼 alert 추가
-
- resolved : #188
> [Fix] DreamLog #188 다크모드 미실행 설정, 전체삭제버튼 alert 추가
